name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install bash clang llvm lld

    - name: Build SDK
      run: |
        make DESTDIR=${{ runner.tool_cache }}/ps4-payload-sdk install
        PS4_PAYLOAD_SDK=${{ runner.tool_cache }}/ps4-payload-sdk ./libcxx.sh
        cd ${{ runner.tool_cache }}
        zip -r $GITHUB_WORKSPACE/ps4-payload-sdk.zip ps4-payload-sdk
        cd -

    - name: Upload SDK
      uses: actions/upload-artifact@v4
      with:
        name: SDK
        path: ./ps4-payload-sdk.zip
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: SDK
          path: .

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: ps4-payload-sdk.zip
